// Dummy product data for the Farm Fresh Market
const dummyProducts = [
    {
        id: 1,
        name: "Fresh Organic Tomatoes",
        description: "Juicy, vine-ripened organic tomatoes. Perfect for salads and cooking.",
        price: 40,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "../../assets/image/p/Tomato.jpg",  // Changed path
        popularity: 4.8,
        is_organic: true,
        discount: 10,
        date_added: "2025-02-15"
    },
    {
        id: 2,
        name: "Crisp Red Apples",
        description: "Sweet and crisp red apples. Great for snacking or baking.",
        price: 120,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Orchard Hills",
        image: "../../assets/image/p/Apple.webp",  // Changed path
        popularity: 4.5,
        is_organic: false,
        discount: 0,
        date_added: "2025-02-20"
    },
    {
        id: 3,
        name: "Free-Range Eggs",
        description: "Farm-fresh eggs from free-range chickens. Rich in flavor and nutrition.",
        price: 80,
        category: "eggs",
        farming_method: "free-range",
        farm_name: "Happy Hen Farm",
        image: "../../assets/image/p/Brown-Eggs.webp",
        popularity: 4.7,
        is_organic: true,
        discount: 5,
        date_added: "2025-03-01"
    },
    {
        id: 4,
        name: "Organic Spinach",
        description: "Nutrient-rich organic spinach leaves. Perfect for salads and cooking.",
        price: 35,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "../../assets/image/p/spinach.jpg",
        popularity: 4.6,
        is_organic: true,
        discount: 0,
        date_added: "2025-03-05"
    },
    {
        id: 5,
        name: "Fresh Chicken",
        description: "Premium quality chicken, raised without antibiotics.",
        price: 180,
        category: "chicken",
        farming_method: "free-range",
        farm_name: "Sunshine Poultry",
        image: "../../assets/image/p/chicken.webp",
        popularity: 4.9,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-10"
    },
    {
        id: 6,
        name: "Fresh Mutton",
        description: "Premium quality Mutton, raised without antibiotics.",
        price: 880,
        category: "mutton",
        farming_method: "free-range",
        farm_name: "None",
        image: "../../assets/image/p/mutton.webp",
        popularity: 4.9,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-10"
    },
    {
        id: 6,
        name: "Fresh Organic Tomatoes",
        description: "Juicy, vine-ripened organic tomatoes. Perfect for salads and cooking.",
        price: 40,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "../../assets/image/p/Tomato.jpg",  // Changed path
        popularity: 4.8,
        is_organic: true,
        discount: 10,
        date_added: "2025-02-15"
    },
    {
        id: 7,
        name: "Crisp Red Apples",
        description: "Sweet and crisp red apples. Great for snacking or baking.",
        price: 120,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Orchard Hills",
        image: "../../assets/image/p/Apple.webp",  // Changed path
        popularity: 4.5,
        is_organic: false,
        discount: 0,
        date_added: "2025-02-20"
    },
    {
        id: 8,
        name: "Free-Range Eggs",
        description: "Farm-fresh eggs from free-range chickens. Rich in flavor and nutrition.",
        price: 80,
        category: "eggs",
        farming_method: "free-range",
        farm_name: "Happy Hen Farm",
        image: "../../assets/image/p/Brown-Eggs.webp",
        popularity: 4.7,
        is_organic: true,
        discount: 5,
        date_added: "2025-03-01"
    },
    {
        id: 9,
        name: "Organic Spinach",
        description: "Nutrient-rich organic spinach leaves. Perfect for salads and cooking.",
        price: 35,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "../../assets/image/p/spinach.jpg",
        popularity: 4.6,
        is_organic: true,
        discount: 0,
        date_added: "2025-03-05"
    },
    {
        id: 10,
        name: "Fresh Chicken",
        description: "Premium quality chicken, raised without antibiotics.",
        price: 180,
        category: "chicken",
        farming_method: "free-range",
        farm_name: "Sunshine Poultry",
        image: "../../assets/image/p/chicken.webp",
        popularity: 4.9,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-10"
    },
    // Added Vegetables
    {
        id: 11,
        name: "Fresh Cauliflower",
        description: "Crisp, white cauliflower with tender florets. Excellent for curries and roasting.",
        price: 45,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Harvest Fields",
        image: "../../assets/image/p/cauliflower.webp",
        popularity: 4.3,
        is_organic: false,
        discount: 5,
        date_added: "2025-03-15"
    },
    {
        id: 12,
        name: "Ladyfinger",
        description: "Dark green, fresh ladyfinger loaded with vitamins and minerals.",
        price: 30,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Riverside Gardens",
        image: "../../assets/image/p/ladyfinger.jpg",
        popularity: 4.4,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-12"
    },
    {
        id: 13,
        name: "Crisp Cabbage",
        description: "Fresh, tightly packed cabbage heads. Great for salads, stir-fries, and fermented dishes.",
        price: 35,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Valley View Farms",
        image: "../../assets/image/p/cabbage.webp",
        popularity: 4.1,
        is_organic: false,
        discount: 8,
        date_added: "2025-03-18"
    },
    {
        id: 14,
        name: "Bell Capsicum Mix",
        description: "Colorful mix of red, yellow, and green bell peppers. Sweet and crunchy, perfect for any dish.",
        price: 60,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Rainbow Produce",
        image: "../../assets/image/p/capsicum.jpg",
        popularity: 4.5,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-20"
    },
    {
        id: 15,
        name: "Green Chilli",
        description: "Spicy green chillies that add the perfect heat to any dish. Locally grown and harvested.",
        price: 20,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Spice Garden",
        image: "../../assets/image/p/chilli.webp",
        popularity: 4.6,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-14"
    },
    {
        id: 16,
        name: "Fresh Green Peas",
        description: "Sweet and tender green peas. Versatile addition to many recipes and rich in protein.",
        price: 50,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "../../assets/image/p/green peas.jpg",
        popularity: 4.7,
        is_organic: true,
        discount: 10,
        date_added: "2025-03-22"
    },
    {
        id: 17,
        name: "Fresh Garlic Bulbs",
        description: "Aromatic garlic bulbs with intense flavor. Essential for countless recipes.",
        price: 25,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Harvest Fields",
        image: "../../assets/image/p/garlic.webp",
        popularity: 4.8,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-10"
    },
    {
        id: 18,
        name: "Farm-Fresh Carrots",
        description: "Plump, juicy carrots with rich flavor. Locally grown and perfect for salads.",
        price: 35,
        category: "vegetables",
        farming_method: "conventional",
        farm_name: "Sunshine Farms",
        image: "../../assets/image/p/carrot.webp",
        popularity: 4.5,
        is_organic: false,
        discount: 5,
        date_added: "2025-03-25"
    },
    // Added Fruits
    {
        id: 19,
        name: "Organic Alphonso Mangoes",
        description: "Premium Alphonso mangoes known for their rich flavor and sweet aroma. The king of fruits.",
        price: 450,
        category: "fruits",
        farming_method: "organic",
        farm_name: "Tropical Paradise",
        image: "../../assets/image/p/mango.webp",
        popularity: 4.9,
        is_organic: true,
        discount: 0,
        date_added: "2025-04-01"
    },
    {
        id: 20,
        name: "Fresh Green Grapes",
        description: "Seedless green grapes with a crisp texture and sweet flavor. Perfect healthy snack.",
        price: 120,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Vineyard Hills",
        image: "../../assets/image/p/Grapes.webp",
        popularity: 4.6,
        is_organic: false,
        discount: 8,
        date_added: "2025-03-28"
    },
    {
        id: 21,
        name: "Juicy Watermelon",
        description: "Sweet, refreshing watermelon with bright red flesh. Perfect for hot summer days.",
        price: 80,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Riverside Gardens",
        image: "../../assets/image/p/watermelon.jpg",
        popularity: 4.7,
        is_organic: false,
        discount: 0,
        date_added: "2025-04-02"
    },
    {
        id: 22,
        name: "Ripe Bananas",
        description: "Sweet, energy-packed bananas. Convenient and nutritious snack for all ages.",
        price: 60,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Tropical Harvest",
        image: "../../assets/image/p/banana.webp",
        popularity: 4.8,
        is_organic: false,
        discount: 5,
        date_added: "2025-03-25"
    },
    {
        id: 23,
        name: "Premium Avocados",
        description: "Creamy, nutrient-rich avocados. Perfect for salads, sandwiches, and making guacamole.",
        price: 180,
        category: "fruits",
        farming_method: "organic",
        farm_name: "Green Grove",
        image: "../../assets/image/p/avocado.jpg",
        popularity: 4.7,
        is_organic: true,
        discount: 0,
        date_added: "2025-03-30"
    },
    {
        id: 24,
        name: "Sweet Chiku (Sapodilla)",
        description: "Brown, sweet fruit with a grainy texture. Rich in natural sugars and dietary fiber.",
        price: 100,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Orchard Hills",
        image: "../../assets/image/p/chiku.webp",
        popularity: 4.2,
        is_organic: false,
        discount: 10,
        date_added: "2025-04-04"
    },
    {
        id: 25,
        name: "Exotic Dragon Fruit",
        description: "Vibrant pink exterior with white flesh and black seeds. Mildly sweet with a refreshing taste.",
        price: 220,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Exotic Fruits Co.",
        image: "../../assets/image/p/dragon fruit.webp",
        popularity: 4.5,
        is_organic: false,
        discount: 0,
        date_added: "2025-04-05"
    },
    {
        id: 26,
        name: "Ripe Papaya",
        description: "Sweet, orange-fleshed papaya rich in vitamins and digestive enzymes.",
        price: 90,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Tropical Paradise",
        image: "../../assets/image/p/papaya.webp",
        popularity: 4.3,
        is_organic: false,
        discount: 5,
        date_added: "2025-04-03"
    },
    // Added Dairy Products
    {
        id: 27,
        name: "Fresh Cow Milk",
        description: "Pure, pasteurized cow milk. Rich in calcium and protein, perfect for daily consumption.",
        price: 65,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Green Meadows Dairy",
        image: "../../assets/image/p/milk.png",
        popularity: 4.8,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-20"
    },
    {
        id: 28,
        name: "Premium Buffalo Milk",
        description: "Creamy buffalo milk with higher fat content. Ideal for making rich dairy products at home.",
        price: 85,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Valley Dairy Farm",
        image: "../../assets/image/p/buffalo milk.webp",
        popularity: 4.6,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-22"
    },
    {
        id: 29,
        name: "Pure Desi Ghee",
        description: "Traditional clarified ghee made from cow's milk. Rich aroma and authentic taste.",
        price: 550,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Heritage Dairy",
        image: "../../assets/image/p/ghee.webp",
        popularity: 4.9,
        is_organic: false,
        discount: 5,
        date_added: "2025-03-15"
    },
    {
        id: 30,
        name: "Fresh Dahi (Yogurt)",
        description: "Creamy, homestyle yogurt with live cultures. Perfect for meals or making lassi.",
        price: 40,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Green Meadows Dairy",
        image: "../../assets/image/p/dahi.webp",
        popularity: 4.7,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-25"
    },
    {
        id: 31,
        name: "Traditional Lassi",
        description: "Refreshing yogurt-based drink available in sweet and salted varieties. Perfect summer refreshment.",
        price: 30,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Heritage Dairy",
        image: "../../assets/image/p/lassi.webp",
        popularity: 4.5,
        is_organic: false,
        discount: 10,
        date_added: "2025-04-01"
    },
    {
        id: 32,
        name: "Sweet Shrikhand",
        description: "Traditional sweetened strained yogurt dessert(shrikhand) with saffron and cardamom. Rich and creamy.",
        price: 120,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Heritage Dairy",
        image: "../../assets/image/p/shrikhand.jpg",
        popularity: 4.6,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-28"
    },
    {
        id: 33,
        name: "Farm Fresh Butter",
        description: "Creamy, salted butter made from pure cow's milk. Perfect for cooking and spreading.",
        price: 95,
        category: "dairy",
        farming_method: "conventional",
        farm_name: "Valley Dairy Farm",
        image: "../../assets/image/p/butter.png",
        popularity: 4.8,
        is_organic: false,
        discount: 5,
        date_added: "2025-03-30"
    }
];

// Add this at the end of the file
export { dummyProducts };