// Dummy product data for the Farm Fresh Market
export const dummyProducts = [
    {
        id: 1,
        name: "Fresh Organic Tomatoes",
        description: "Juicy, vine-ripened organic tomatoes. Perfect for salads and cooking.",
        price: 40,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "/assets/image/Products/tomato.jpg",
        popularity: 4.8,
        is_organic: true,
        discount: 10,
        date_added: "2025-02-15"
    },
    {
        id: 2,
        name: "Crisp Red Apples",
        description: "Sweet and crisp red apples. Great for snacking or baking.",
        price: 120,
        category: "fruits",
        farming_method: "conventional",
        farm_name: "Orchard Hills",
        image: "/assets/image/Products/apple.png",
        popularity: 4.5,
        is_organic: false,
        discount: 0,
        date_added: "2025-02-20"
    },
    {
        id: 3,
        name: "Free-Range Eggs",
        description: "Farm-fresh eggs from free-range chickens. Rich in flavor and nutrition.",
        price: 80,
        category: "eggs",
        farming_method: "free-range",
        farm_name: "Happy Hen Farm",
        image: "/assets/image/Products/Egg.png",
        popularity: 4.7,
        is_organic: true,
        discount: 5,
        date_added: "2025-03-01"
    },
    {
        id: 4,
        name: "Organic Spinach",
        description: "Nutrient-rich organic spinach leaves. Perfect for salads and cooking.",
        price: 35,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Green Valley Farms",
        image: "/assets/image/Products/spinach.jpg",
        popularity: 4.6,
        is_organic: true,
        discount: 0,
        date_added: "2025-03-05"
    },
    {
        id: 5,
        name: "Fresh Chicken",
        description: "Premium quality chicken, raised without antibiotics.",
        price: 180,
        category: "chicken",
        farming_method: "free-range",
        farm_name: "Sunshine Poultry",
        image: "/assets/image/Products/chicken.png",
        popularity: 4.9,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-10"
    },
    {
        id: 6,
        name: "Organic Carrots",
        description: "Sweet and crunchy organic carrots. Great for snacking and cooking.",
        price: 30,
        category: "vegetables",
        farming_method: "organic",
        farm_name: "Roots & Greens",
        image: "/assets/image/Products/carrot.jpg",
        popularity: 4.4,
        is_organic: true,
        discount: 0,
        date_added: "2025-03-12"
    },
    {
        id: 7,
        name: "Fresh Mutton",
        description: "High-quality mutton from grass-fed sheep.",
        price: 350,
        category: "mutton",
        farming_method: "conventional",
        farm_name: "Highland Pastures",
        image: "/assets/image/Products/mutton.jpg",
        popularity: 4.7,
        is_organic: false,
        discount: 5,
        date_added: "2025-03-15"
    },
    {
        id: 8,
        name: "Organic Bananas",
        description: "Sweet and ripe organic bananas. Perfect for snacking and smoothies.",
        price: 60,
        category: "fruits",
        farming_method: "organic",
        farm_name: "Tropical Harvest",
        image: "/assets/image/Products/banana.jpg",
        popularity: 4.5,
        is_organic: true,
        discount: 0,
        date_added: "2025-03-18"
    },
    {
        id: 9,
        name: "Fresh Fish",
        description: "Freshly caught fish. Rich in omega-3 fatty acids.",
        price: 220,
        category: "fish",
        farming_method: "conventional",
        farm_name: "Ocean Harvest",
        image: "/assets/image/Products/fish.jpg",
        popularity: 4.6,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-20"
    },
    {
        id: 10,
        name: "Hydroponic Lettuce",
        description: "Crisp and fresh lettuce grown using hydroponic methods.",
        price: 45,
        category: "vegetables",
        farming_method: "hydroponic",
        farm_name: "Future Farms",
        image: "/assets/image/Products/lettuce.jpg",
        popularity: 4.3,
        is_organic: false,
        discount: 0,
        date_added: "2025-03-25"
    }
];
